// Mira client service.
//
// The React layer talks only to the /api/mira endpoints and never to a speech
// or AI provider directly. The Firebase ID token is attached by this module, and
// the server derives the UID from the verified token.
//
// Conversation data is stored separately from Health History and Medical
// Records, under users/{uid}/miraConversations. Nothing generated by Mira is
// written into clinical records.

import { addDoc, collection, doc, getDocs, limit as firestoreLimit, orderBy, query, serverTimestamp, setDoc } from 'firebase/firestore';
import { auth, db } from '../firebase-init';
import {
  DEFAULT_MIRA_LANGUAGE,
  MIRA_LANGUAGE_STORAGE_KEY,
  MIRA_VOICE_CAPABILITY_KEY,
  isMiraLanguageCode,
  resolveMiraVoiceCapability,
  type MiraLanguageCode,
} from './miraConfig';

export type MiraMessageRole = 'user' | 'assistant';
export type MiraMessageSource = 'text' | 'voice';

export interface MiraChatMessage {
  id: string;
  role: MiraMessageRole;
  text: string;
  source: MiraMessageSource;
  createdAt: string;
}

export type MiraEscalationUrgency = 'none' | 'specialist' | 'urgent';

export interface MiraEscalation {
  needed: boolean;
  urgency: MiraEscalationUrgency;
  reason: string;
  matchedRedFlags: string[];
}

export interface MiraHandoffDraft {
  concern: string;
  duration: string;
  symptoms: string[];
  medications: string[];
  hydration: string;
  reason: string;
  summaryText: string;
}

export interface MiraChatResult {
  reply: string;
  language: MiraLanguageCode;
  escalation: MiraEscalation;
  handoff: MiraHandoffDraft | null;
  handoffLabel: string;
  emergencyGuidance: string | null;
  provider: { model: string };
}

export type MiraSaveState = 'recorded' | 'device-only' | 'unavailable';

export class MiraApiError extends Error {
  readonly code: string;
  readonly status: number;

  constructor(code: string, message: string, status: number) {
    super(message);
    this.name = 'MiraApiError';
    this.code = code;
    this.status = status;
  }
}

function readErrorMessage(payload: unknown, fallback: string): string {
  const candidate = payload as { error?: { message?: unknown } };
  return typeof candidate?.error?.message === 'string' && candidate.error.message.trim()
    ? candidate.error.message
    : fallback;
}

async function miraFetch<T>(path: string, body: Record<string, unknown>): Promise<T> {
  const currentUser = auth.currentUser;
  if (!currentUser) {
    throw new MiraApiError('unauthenticated', 'Sign in again to use Mira.', 401);
  }
  const token = await currentUser.getIdToken();

  let response: Response;
  try {
    response = await fetch(path, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify(body),
    });
  } catch {
    throw new MiraApiError('network', 'Mira could not be reached. Check your connection and try again.', 0);
  }

  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    const candidate = payload as { error?: { code?: unknown } };
    const code = typeof candidate?.error?.code === 'string' ? candidate.error.code : 'mira_unavailable';
    throw new MiraApiError(code, readErrorMessage(payload, 'Mira could not complete that request.'), response.status);
  }
  return payload as T;
}

export function readStoredMiraLanguage(): MiraLanguageCode {
  try {
    const stored = localStorage.getItem(MIRA_LANGUAGE_STORAGE_KEY);
    return isMiraLanguageCode(stored) ? stored : DEFAULT_MIRA_LANGUAGE;
  } catch {
    return DEFAULT_MIRA_LANGUAGE;
  }
}

export function storeMiraLanguage(language: MiraLanguageCode) {
  try {
    localStorage.setItem(MIRA_LANGUAGE_STORAGE_KEY, language);
  } catch {
    // Storage may be unavailable; the in-memory selection still applies.
  }
}

/** Neutral capability flag. Voice stays demonstrable and can be disabled explicitly. */
export function isVoiceEnabledForClient(): boolean {
  try {
    return resolveMiraVoiceCapability(localStorage.getItem(MIRA_VOICE_CAPABILITY_KEY));
  } catch {
    return true;
  }
}

export async function sendMiraMessage(input: {
  conversationId: string;
  language: MiraLanguageCode;
  message: string;
  source: MiraMessageSource;
  history: Array<{ role: MiraMessageRole; text: string }>;
}): Promise<MiraChatResult> {
  return miraFetch<MiraChatResult>('/api/mira/chat', input);
}

export async function transcribeMiraAudio(input: {
  language: MiraLanguageCode;
  audioBase64: string;
  mimeType: string;
}): Promise<{ transcript: string; language: MiraLanguageCode; provider: { model: string } }> {
  return miraFetch('/api/mira/transcribe', input);
}

export async function synthesizeMiraSpeech(input: {
  language: MiraLanguageCode;
  text: string;
}): Promise<{ audioBase64: string; mimeType: string; provider: { model: string } }> {
  return miraFetch('/api/mira/speak', input);
}

export interface MiraStoredConversation {
  conversationId: string;
  language: MiraLanguageCode;
  updatedAt: string;
  messages: MiraChatMessage[];
}

const MIRA_DEVICE_CONVERSATION_PREFIX = 'warrior_mira_conversation_';
const MIRA_STORED_MESSAGE_LIMIT = 40;

export function generateMiraConversationId(): string {
  return `mira-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

export function generateMiraMessageId(): string {
  return `msg-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function deviceConversationKey(userId: string) {
  return `${MIRA_DEVICE_CONVERSATION_PREFIX}${userId}`;
}

function toIsoString(value: unknown): string {
  const candidate = value as { toDate?: () => Date };
  if (candidate && typeof candidate.toDate === 'function') {
    return candidate.toDate().toISOString();
  }
  return typeof value === 'string' ? value : new Date().toISOString();
}

function readDeviceConversation(userId: string): MiraStoredConversation | null {
  if (!userId) return null;
  try {
    const raw = localStorage.getItem(deviceConversationKey(userId));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<MiraStoredConversation>;
    if (!parsed?.conversationId || !Array.isArray(parsed.messages)) return null;
    return {
      conversationId: parsed.conversationId,
      language: isMiraLanguageCode(parsed.language) ? parsed.language : DEFAULT_MIRA_LANGUAGE,
      updatedAt: typeof parsed.updatedAt === 'string' ? parsed.updatedAt : new Date().toISOString(),
      messages: parsed.messages.filter((message): message is MiraChatMessage => typeof message?.text === 'string'),
    };
  } catch {
    return null;
  }
}

function writeDeviceConversation(userId: string, conversation: MiraStoredConversation): boolean {
  if (!userId) return false;
  try {
    const trimmed = { ...conversation, messages: conversation.messages.slice(-MIRA_STORED_MESSAGE_LIMIT) };
    localStorage.setItem(deviceConversationKey(userId), JSON.stringify(trimmed));
    return true;
  } catch {
    return false;
  }
}

/**
 * Starts a Mira conversation record. Mira conversations are intentionally kept
 * separate from Health History and Medical Records and are never written into
 * them.
 */
export async function startMiraConversation(input: {
  userId: string;
  conversationId: string;
  language: MiraLanguageCode;
  mode: MiraMessageSource;
}): Promise<MiraSaveState> {
  const { userId, conversationId, language, mode } = input;
  const savedOnDevice = writeDeviceConversation(userId, {
    conversationId,
    language,
    updatedAt: new Date().toISOString(),
    messages: readDeviceConversation(userId)?.messages ?? [],
  });
  try {
    await setDoc(
      doc(db, 'users', userId, 'miraConversations', conversationId),
      { language, mode, escalationUrgency: 'none', createdAt: serverTimestamp(), updatedAt: serverTimestamp() },
      { merge: true },
    );
    return 'recorded';
  } catch {
    return savedOnDevice ? 'device-only' : 'unavailable';
  }
}

/**
 * Persists one Mira message. Only role, text, source and time are stored —
 * never raw audio, and never a copy into clinical records.
 */
export async function saveMiraMessage(input: {
  userId: string;
  conversationId: string;
  message: MiraChatMessage;
  language: MiraLanguageCode;
  escalationUrgency: MiraEscalationUrgency;
}): Promise<MiraSaveState> {
  const { userId, conversationId, message, language, escalationUrgency } = input;
  const deviceExisting = readDeviceConversation(userId);
  const deviceMessages = deviceExisting?.conversationId === conversationId ? deviceExisting.messages : [];
  const savedOnDevice = writeDeviceConversation(userId, {
    conversationId,
    language,
    updatedAt: message.createdAt,
    messages: [...deviceMessages, message],
  });

  try {
    await setDoc(
      doc(db, 'users', userId, 'miraConversations', conversationId),
      { language, escalationUrgency, updatedAt: serverTimestamp() },
      { merge: true },
    );
    await addDoc(collection(db, 'users', userId, 'miraConversations', conversationId, 'messages'), {
      role: message.role,
      text: message.text,
      source: message.source,
      createdAt: serverTimestamp(),
    });
    return 'recorded';
  } catch {
    return savedOnDevice ? 'device-only' : 'unavailable';
  }
}

export async function loadLatestMiraConversation(userId: string): Promise<MiraStoredConversation | null> {
  if (!userId) return null;
  try {
    const conversations = await getDocs(
      query(collection(db, 'users', userId, 'miraConversations'), orderBy('updatedAt', 'desc'), firestoreLimit(1)),
    );
    if (!conversations.empty) {
      const conversationDoc = conversations.docs[0];
      const conversationData = conversationDoc.data();
      const messageSnapshot = await getDocs(
        query(
          collection(db, 'users', userId, 'miraConversations', conversationDoc.id, 'messages'),
          orderBy('createdAt', 'desc'),
          firestoreLimit(MIRA_STORED_MESSAGE_LIMIT),
        ),
      );
      const messages = messageSnapshot.docs.map((entry) => {
        const raw = entry.data();
        return {
          id: entry.id,
          role: raw.role === 'assistant' ? ('assistant' as const) : ('user' as const),
          text: typeof raw.text === 'string' ? raw.text : '',
          source: raw.source === 'voice' ? ('voice' as const) : ('text' as const),
          createdAt: toIsoString(raw.createdAt),
        };
      }).reverse();
      return {
        conversationId: conversationDoc.id,
        language: isMiraLanguageCode(conversationData.language)
          ? conversationData.language
          : DEFAULT_MIRA_LANGUAGE,
        updatedAt: toIsoString(conversationData.updatedAt),
        messages,
      };
    }
  } catch {
    // Fall through to the device copy below.
  }
  return readDeviceConversation(userId);
}
